### ISSUE TITLE
Use Collections name If Collection SelectedB

### ISSUE THREAD

**Issue by MrPositivity** [DigiKrafting/blender_addon_substance_painter#12]
Can it be made that if I Select Collection, Export will use Collections name? 
This is done because I use Collections as Groups and name them appropriately like cube_h and cube_l 
Then when I export I need thous names to be my File names. Right now it just reads Objects name, but most of the models consist of multiple objects so I think Object name only needs to be used if one Object is selected. 
Would this be possible to implement ?

**Comment by DigiKrafting** [comment]
Sure thing, I can see how this would be useful, I'll add the requested feature in the next few days.

**Comment by DigiKrafting** [comment]
Hi MrPositivity, I've added the option to export selected collection: [https://github.com/DigiKrafting/blender_addon_substance_painter/releases/latest](https://github.com/DigiKrafting/blender_addon_substance_painter/releases/latest)
