### ISSUE TITLE
Every time I try to export anything, I get this error

### ISSUE THREAD

**Issue by IronLover64** [DigiKrafting/blender_addon_substance_painter#13]
![Screenshot (67)](https://user-images.githubusercontent.com/51809607/76147577-b99c0b00-606b-11ea-9a58-2dc58dcb36dd.png)

**Comment by DigiKrafting** [comment]
Hi IronLover64, thanks for reporting the error, I've uploaded a fix: [https://github.com/DigiKrafting/blender_addon_substance_painter/releases/latest](https://github.com/DigiKrafting/blender_addon_substance_painter/releases/latest)
