### ISSUE TITLE
Shader nodes aren't created

### ISSUE THREAD

**Issue by PaulJManoogian** [DigiKrafting/blender_addon_substance_painter#4]
While testing the plug-in on Blender 2.8 RC1 with Substance Painter 2019.1.3, None of the shader nodes are created when bringing the scene or selections back in from Substance Painter.

Also, I don't have the buttons for FBX, OBJ, etc... Maybe I'm just missing something there.

**Comment by PaulJManoogian** [comment]
My error... I hadn't exported the textures from SP.

**Comment by DigiKrafting** [comment]
I'm currently using Blender 2.8 RC1 and Substance Painter 2019.1.3 without any known issues.

The buttons are added to the top toolbar if the "Display Type" is set to "Buttons" in the addon prefences, see the screenshot I've added. FBX or OBJ is set in the addon preferences under "Export Type", see in the bottom screenshot.

**Comment by PaulJManoogian** [comment]
All Good! I figured it out, thank you for your response!  I love what you've done here. It certainly helps my workflow!
