### ISSUE TITLE
the import button not work. i can not get the texture back.

### ISSUE THREAD

**Issue by genics** [DigiKrafting/blender_addon_substance_painter#6]
can you make a mini tutorial how to use this addon?

**Comment by genics** [comment]
ok.it work now, so this addon just work at unreal engine 4 preset. right?
btw this is a great addon! thanks

**Comment by DigiKrafting** [comment]
I'm happy to create a tutorial. Unreal engine textures are optional, I added to save time when working on assets for unreal, it allows me to avoid having to export two separate texture sets from SP, one set for blender and one set for unreal. Thanks, your welcome :)
