### ISSUE TITLE
Can't get importing to work

### ISSUE THREAD

**Issue by justifun** [DigiKrafting/blender_addon_substance_painter#8]
The SP Scene/Sel buttons work for sending the object to substance painter, but i can't seem to get the import buttons to work.

There doesnt seem to be any errors or anything in the console log

**Comment by DigiKrafting** [comment]
Are you using SP 2018.1.0 to 2018.3.0? In SP 2018.1.0 to 2018.3.0 the project file name sent from blender is appended to the textures export path in SP which causes the addon not to know where the textures were created, please make sure you tick "2018.1.0-2018.3.0 Project File Fix" in the addon preferences and check the folder that is set in SP when exporting textures.

**Comment by justifun** [comment]
I'm using 2019.2.0.  I think i sorta got it working.  I needed to make sure to save the blend file and export the textures from SP before using the blender import button.

Next question for you is What is the correct order of operations if you already have the model imported in SP and painted, but you are sending the object to blender for the first time.

I can make an object in blender, and send it to substance and paint it and send it back textured, but what if you started in SP instead of blender?

**Comment by DigiKrafting** [comment]
Import the object you used in SP into blender and save the blender file in the same location as the SP project file (.spp). SP's default export folder is "Textures" as is this addon's or rename the an existing folder to "Textures" or put textures into a folder named "Textures", you should then be able to then import the textures
