### ISSUE TITLE
Does not work in Blender 2.81 alpha from 4th sep, 14:30

### ISSUE THREAD

**Issue by redemprez** [DigiKrafting/blender_addon_substance_painter#9]
The path to Painter is provided in plugin preferences, although, when you press "Send to SP" button you get error message and the model is not exported:

EDIT: FBX export is not working, OBJ export still works.

![image](https://user-images.githubusercontent.com/25802640/64284759-9c6e6e80-cf5a-11e9-8fe9-af226627dfd6.png)

**Comment by DigiKrafting** [comment]
Hi redemprez,

Thanks for reporting the error, I've uploaded a fix, please find at:

https://github.com/DigiKrafting/blender_addon_substance_painter/releases/tag/1_8_1
